/* Generated by scripts/generate-tokens.mjs from tokens.source.ts. Do not edit. */
/* eslint-disable */

/**
 * The two motion families. Every animation declares which one it belongs to:
 * `springObject` for anything with a physical metaphor, `ease.info` with a
 * duration for anything that is purely informational.
 */
export const motion = {
  "springObject": {
    "stiffness": 180,
    "damping": 26,
    "mass": 1
  },
  "springSurface": {
    "stiffness": 120,
    "damping": 24,
    "mass": 1.1
  },
  "duration": {
    "feedback": "120ms",
    "state": "220ms",
    "theme": "240ms",
    "reveal": "320ms",
    "navigation": "760ms"
  },
  "ease": {
    "object": "cubic-bezier(.22, 1, .36, 1)",
    "info": "cubic-bezier(.2, .8, .2, 1)",
    "navigation": "cubic-bezier(.22, .72, .16, 1)"
  }
} as const;

/**
 * The same two scales in the units Motion takes. Derived here rather than
 * retyped at the call sites, which is what the CSS strings above were quietly
 * forcing every JS animation to do.
 */
export const durationMs = {
  "feedback": 120,
  "state": 220,
  "theme": 240,
  "reveal": 320,
  "navigation": 760
} as const;

export const easePoints = {
  "object": [
    0.22,
    1,
    0.36,
    1
  ],
  "info": [
    0.2,
    0.8,
    0.2,
    1
  ],
  "navigation": [
    0.22,
    0.72,
    0.16,
    1
  ]
} as const;
