/* Generated by scripts/generate-tokens.mjs from tokens.source.ts. Do not edit. */
/* eslint-disable */

/** Numeric radii, for Motion's layout scale correction. */
export const radius = {
  "s": 8,
  "m": 16,
  "l": 24,
  "pill": 999
} as const;

/** Spacing as numbers, for animated offsets that cannot read a CSS variable. */
export const space = {
  "0": 0,
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 24,
  "6": 32,
  "7": 48,
  "8": 64,
  "hair": 2
} as const;

export const elevation = {
  "day": {
    "1": "0 1px 2px rgb(74 55 39 / .10), 0 2px 6px rgb(74 55 39 / .08)",
    "2": "0 2px 4px rgb(74 55 39 / .12), 0 10px 24px rgb(74 55 39 / .14)",
    "3": "0 4px 8px rgb(74 55 39 / .14), 0 28px 64px rgb(74 55 39 / .22)"
  },
  "night": {
    "1": "0 1px 2px rgb(0 0 0 / .34), 0 2px 6px rgb(0 0 0 / .28), inset 0 1px 0 rgb(255 183 87 / .05)",
    "2": "0 2px 4px rgb(0 0 0 / .40), 0 10px 24px rgb(0 0 0 / .36), 0 0 28px rgb(255 183 87 / .05)",
    "3": "0 4px 8px rgb(0 0 0 / .46), 0 28px 64px rgb(0 0 0 / .52), 0 0 70px rgb(255 183 87 / .09)"
  }
} as const;
export const accentElevation = {
  "rest": "0 9px 22px color-mix(in srgb, var(--accent) 24%, transparent)",
  "hover": "0 13px 30px color-mix(in srgb, var(--accent) 30%, transparent)",
  "press": "0 5px 12px color-mix(in srgb, var(--accent) 22%, transparent)"
} as const;

/**
 * The two motion families. Every animation declares which one it belongs to:
 * `springObject` for anything with a physical metaphor, `ease.info` with a
 * duration for anything that is purely informational.
 */
export const motion = {
  "springObject": {
    "stiffness": 180,
    "damping": 26,
    "mass": 1
  },
  "springSurface": {
    "stiffness": 120,
    "damping": 24,
    "mass": 1.1
  },
  "duration": {
    "feedback": "120ms",
    "state": "220ms",
    "theme": "240ms",
    "reveal": "320ms",
    "navigation": "760ms"
  },
  "ease": {
    "object": "cubic-bezier(.22, 1, .36, 1)",
    "info": "cubic-bezier(.2, .8, .2, 1)",
    "navigation": "cubic-bezier(.22, .72, .16, 1)"
  }
} as const;

export type SpaceStep = keyof typeof space;
export type RadiusStep = keyof typeof radius;
