#!/usr/bin/env node
/**
 * Emits the two token artifacts from src/design/tokens.source.ts.
 *
 *   src/design/tokens.generated.css  custom properties for styles.css
 *   src/design/tokens.generated.ts   runtime motion constants for React
 *
 * Both are checked in so the build never depends on this script running, and
 * `npm run tokens:check` fails when they have drifted from the source.
 *
 * Requires Node >= 22.6 for TypeScript type stripping, which lets the source of
 * truth keep its types instead of being demoted to plain JavaScript.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const designDir = join(here, "..", "src", "design");

const tokens = await import(join(designDir, "tokens.source.ts"));

const BANNER = `/* Generated by scripts/generate-tokens.mjs from tokens.source.ts. Do not edit. */`;

function cssBlock(lines, indent = "  ") {
  return lines.map((line) => (line === "" ? "" : `${indent}${line}`)).join("\n");
}

function buildCss() {
  const { type, weight, track, family, radius, shape, space, spaceFluid, elevation, ring, bookShadow, accentElevation, motion, color } = tokens;

  const dayVars = [
    "/* — color ————————————————————————————————— */",
    ...Object.entries(color.day).map(([name, value]) => `--${name}: ${value};`),
    "",
    "/* — type ——————————————————————————————————— */",
    ...Object.entries(family).map(([name, value]) => `--font-${name}: ${value};`),
    ...Object.entries(weight).map(([name, value]) => `--weight-${name}: ${value};`),
    ...Object.entries(track).map(([name, value]) => `--${name}: ${value};`),
    ...Object.entries(type).flatMap(([name, step]) => [
      `--text-${name}: ${step.size};`,
      `--leading-${name}: ${step.line};`,
    ]),
    "",
    "/* — radius —————————————————————————————————— */",
    ...Object.entries(radius).map(([name, value]) => `--radius-${name}: ${value}px;`),
    ...Object.entries(shape).map(([name, value]) => `--shape-${name}: ${value};`),
    "",
    "/* — space ——————————————————————————————————— */",
    ...Object.entries(space).map(([name, value]) => `--space-${name}: ${value};`),
    `--space-fluid: ${spaceFluid};`,
    "",
    "/* — elevation ——————————————————————————————— */",
    ...Object.entries(elevation.day).map(([step, value]) => `--elev-${step}: ${value};`),
    ...Object.entries(ring).map(([name, value]) => `--ring-${name}: ${value.day};`),
    `--elev-book: ${bookShadow.rest.day};`,
    `--elev-book-hover: ${bookShadow.hover.day};`,
    ...Object.entries(accentElevation).map(([name, value]) => `--elev-accent-${name}: ${value};`),
    "",
    "/* — motion —————————————————————————————————— */",
    ...Object.entries(motion.duration).map(([name, value]) => `--motion-${name}: ${value};`),
    ...Object.entries(motion.ease).map(([name, value]) => `--ease-${name}: ${value};`),
  ];

  const nightVars = [
    ...Object.entries(color.night).map(([name, value]) => `--${name}: ${value};`),
    ...Object.entries(elevation.night).map(([step, value]) => `--elev-${step}: ${value};`),
    ...Object.entries(ring).map(([name, value]) => `--ring-${name}: ${value.night};`),
    `--elev-book: ${bookShadow.rest.night};`,
    `--elev-book-hover: ${bookShadow.hover.night};`,
  ];

  return `${BANNER}

:root {
${cssBlock(dayVars)}
}

:root[data-theme="night"] {
${cssBlock(nightVars)}
}
`;
}

function buildTs() {
  const { motion } = tokens;
  const literal = (value) => JSON.stringify(value, null, 2);

  return `${BANNER}
/* eslint-disable */

/**
 * The two motion families. Every animation declares which one it belongs to:
 * \`springObject\` for anything with a physical metaphor, \`ease.info\` with a
 * duration for anything that is purely informational.
 */
export const motion = ${literal(motion)} as const;

/**
 * The same two scales in the units Motion takes. Derived here rather than
 * retyped at the call sites, which is what the CSS strings above were quietly
 * forcing every JS animation to do.
 */
export const durationMs = ${literal(
    Object.fromEntries(Object.entries(motion.duration).map(([k, v]) => [k, Number.parseFloat(String(v))])),
  )} as const;

export const easePoints = ${literal(
    Object.fromEntries(
      Object.entries(motion.ease).map(([k, v]) => [
        k,
        String(v)
          .replace(/^cubic-bezier\(|\)$/g, "")
          .split(",")
          .map((n) => Number.parseFloat(n)),
      ]),
    ),
  )} as const;
`;
}

const targets = [
  [join(designDir, "tokens.generated.css"), buildCss()],
  [join(designDir, "tokens.generated.ts"), buildTs()],
];

const check = process.argv.includes("--check");
let drifted = false;

for (const [path, next] of targets) {
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = null;
  }
  if (current === next) continue;
  if (check) {
    drifted = true;
    console.error(`token drift: ${path.replace(`${join(here, "..")}/`, "")} is stale. Run \`npm run tokens\`.`);
    continue;
  }
  writeFileSync(path, next);
  console.log(`wrote ${path.replace(`${join(here, "..")}/`, "")}`);
}

if (drifted) process.exit(1);
if (check) console.log("tokens are in sync with tokens.source.ts");
